version: "3.8"
services:
  node:
    build: ./docker/node
    volumes:
      - ".:/usr/src/app/"
    command: npm start
    ports:
      - "9000:9000"
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    environment:
      MONGODB_USERNAME: root
      MONGO_PASSWORD: root
      MONGO_DATABASE: halgo
