version: "3.8"
services:
  nodeserver:
    build: ./docker/node
    ports:
      - "9001:9001"
    volumes:
      - "./NodesServer:/usr/src/app/"
    links:
      - mongodb
    command: npm start
    # command: tail -f /dev/null
  node-react:
    build: ./docker/node
    volumes:
      - "./Node:/usr/src/app/"
    links:
      - "node"
    depends_on:
      - nodeserver
    deploy:
      replicas: 1
    ports:
      - "5000:5000"
    command: npm start
  node:
    build: ./docker/node
    volumes:
      - "./Node:/usr/src/app/"
    depends_on:
      - nodeserver
    deploy:
      replicas: 2
    command: npm start
  front-react:
    build: ./docker/react
    restart: always
    depends_on:
      - nodeserver
      - node
    volumes:
      - "./front-blockchain:/usr/src/app/"
    command: yarn start
    ports:
      - "3000:3000"
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: halgo
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
