version: "3.8"
services:
  nodeserver:
    build: ./docker/node
    ports:
      - "9001:9001"
    volumes:
      - "./NodesServer:/usr/src/app/"
    depends_on:
      - mongodb
    command: npm start
    #command: tail -f /dev/null
  node:
    build: ./docker/node
    volumes:
      - "./Node:/usr/src/app/"
    depends_on:
      - nodeserver
    deploy:
      replicas: 10
    command: npm start
  mongodb:
    image: "mongo"
    ports:
      - "27017:27017"
    environment:
      MONGODB_USERNAME: root
      MONGO_PASSWORD: root
      MONGO_DATABASE: halgo
